version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cryptoNews"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2vv85ofdlkae"
s3_prefix = "cryptoNews"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
